### ISSUE TITLE
Lint fix broke plugin

### ISSUE THREAD

**Issue by davidhao3300** [istio-ecosystem/cni#30]
https://github.com/istio-ecosystem/cni/commit/9d0c12b97f0fbecececa486c538feb7b7e54e198#diff-979edba6da78fdae13eaae699dcd86d3R83 causes the args parsing to break.
The Kubernetes arguments there (what used to be K8S_POD_NAMESPACE, etc.) are no longer parsed, and so the plugin ignores all Kubernetes pods.

**Comment by tiswanso** [comment]
Fixed under issue #35
